import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — GiftButler",
  description: "Terms of Service for GiftButler.",
  twitter: { card: "summary" },
};

export default function TermsPage() {
  const updated = "March 18, 2026";

  return (
    <main className="min-h-screen bg-white">
      <nav className="flex items-center justify-between px-6 py-4 max-w-3xl mx-auto border-b border-stone-100">
        <Link href="/" className="text-xl font-bold text-stone-900">GiftButler</Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-stone-900 mb-2">Terms of Service</h1>
        <p className="text-stone-400 text-sm mb-10">Last updated: {updated}</p>

        <div className="space-y-8 text-stone-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">1. Acceptance of terms</h2>
            <p className="text-sm">By using GiftButler (&ldquo;the Service&rdquo;), you agree to these Terms of Service. If you do not agree, do not use the Service. We may update these terms at any time; continued use constitutes acceptance of any changes.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">2. Description of service</h2>
            <p className="text-sm">GiftButler is a free platform that lets users create public gift-hint profiles and share them with others. Visitors can use AI-generated recommendations to find gifts, including links to products on Amazon.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">3. Amazon affiliate disclosure</h2>
            <p className="text-sm">GiftButler participates in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com. When you click an Amazon link and make a purchase, GiftButler may earn a small commission at no additional cost to you. Amazon, the Amazon logo, and related marks are trademarks of Amazon.com, Inc. or its affiliates.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">4. User content</h2>
            <p className="text-sm mb-2">You are responsible for any content (hints, bio, username) you post. By posting content, you grant GiftButler a non-exclusive, royalty-free license to display it as part of the Service.</p>
            <p className="text-sm">You agree not to post content that is unlawful, harmful, defamatory, or that violates any third party&apos;s rights.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">5. Public profiles</h2>
            <p className="text-sm">Your gift profile, including your username, display name, bio, and hints, is public by default and accessible to anyone with your link. Only share information you are comfortable making public.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">6. AI-generated recommendations</h2>
            <p className="text-sm">Gift recommendations are generated by AI and are provided for convenience only. GiftButler makes no warranty that any recommended product is accurate, in stock, correctly priced, or suitable for any particular purpose. Always verify product details before purchasing.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">7. Disclaimer of warranties</h2>
            <p className="text-sm">The Service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. GiftButler does not warrant that the Service will be uninterrupted, error-free, or free of harmful components.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">8. Limitation of liability</h2>
            <p className="text-sm">To the fullest extent permitted by law, GiftButler shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including any purchases made via affiliate links.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">9. Termination</h2>
            <p className="text-sm">We reserve the right to suspend or terminate accounts that violate these terms or that we determine, at our sole discretion, are harmful to the Service or its users.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-stone-900 mb-3">10. Contact</h2>
            <p className="text-sm">Questions about these terms? Email <a href="mailto:privacy@giftbutler.io" className="text-amber-600 hover:underline">privacy@giftbutler.io</a>.</p>
          </section>

        </div>
      </div>

      <footer className="border-t border-stone-100 py-6 text-center text-stone-400 text-sm mt-8">
        <Link href="/" className="hover:text-stone-600">← Back to GiftButler</Link>
      </footer>
    </main>
  );
}
